### ISSUE TITLE
Exposed Quay.io credentials

### ISSUE THREAD

**Issue by rht-lhajn** [moolen/juno#1]
Hello,

We've received a report we'd like to bring your attention to. It appears this repository contains Quay.io credentials:

https://github.com/moolen/juno/blob/6aee3ff394d1d4fd7970f2cabb903d5c8e8f12fd/hack/hubble-demo.yaml#L10

Best regards

**Comment by moolen** [comment]
Thanks for raising this, i think this is a non-issue.

This is a demo app, taken from cilium/hubble repository.
